version: '3.2'

services:
  homeassistant:
    container_name: js-homeassist
    restart: unless-stopped
    image: linuxserver/homeassistant:latest
    network_mode: host
    ports:
      - 8123:8123
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/docker/homeassistant/config:/config
