version: '3.3'

services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: js-mariadb
    #hostname: 'js-mariadb'
    restart: unless-stopped
    networks:
      - nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=nextcloud
      #- POSTGRES_DB=nextcloud
      #- POSTGRES_USER=nextcloud
      #- POSTGRES_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    ports:
      - 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nextcloud_disk/nextcloud/mariadb:/config
    #- /home/pi/docker/nextcloud/postgres:/var/lib/postgresql/data

  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: js-nextcloud
    restart: unless-stopped
    networks:
      - nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      #- POSTGRES_DB=nextcloud
      #- POSTGRES_USER=nextcloud
      #- POSTGRES_PASSWORD=password
      #- POSTGRES_HOST=js-postgres
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=localhost
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    ports:
      - 8081:443
    volumes:
      - /mnt/nextcloud_disk/nextcloud/config:/config
      - /mnt/nextcloud_disk/nextcloud/data:/data
      #- /home/pi/docker/nextcloud/nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      #- postgresdb
      - mariadb

networks: 
  nextcloud:
    driver: bridge
