version: '3.3'

services:
  wireguard:
    container_name: js-wireguard
    restart: unless-stopped
    image: linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=124
      - TZ=Europe/Lisbon
      - SERVERURL=jss-server.duckdns.org
      - SERVERPORT=51820
      - PEERS=myPhone
      - PEERSDNS=1.1.1.1
      - INTERNAL_SUBNET=10.10.10.1
      - ALLOWEDDIPS=0.0.0.0/0
    ports:
      - 51820:51820/udp
    volumes:
      - /home/pi/docker/wireguard/config:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    sysctls: 
      - net.ipv4.conf.all.src_valid_mark=1

